services: 
  database:
    image: postgres:15
    hostname: sb-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file: .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sunbeam

  strapi:
    build: ./backend/ 
    image: strapi/strapi
    hostname: sb-strapi
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      DATABASE_HOST: sb-database
      DATABASE_PORT: 5432
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on: 
      - database 
    volumes:
      - ./app:/srv/app
      - ./backend/public:/app/public
    ports:
      - "1337:1337"
    networks:
      - sunbeam

  frontend:
    build: frontend
    hostname: sb-frontend
    env_file: ./frontend/.env
    # volumes:
    #   - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - sunbeam

volumes:
  database_data:

networks:
  sunbeam:
